- id: vsperf
  type: group
  role: [vsperf]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [hiera, setup_repositories, fuel_pkgs, globals, tools, logging, vsperf_install]
  parameters:
    strategy:
      type: parallel
- id: vsperf_install
  type: puppet
  version: 2.0.0
  groups: [vsperf]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/vsperf-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
